argument_specs:
    main:
        options:
            wildfly_user:
                default: "wildfly"
                description: "posix user account for wildfly"
                type: "str"
            wildfly_group:
                default: "{{ wildfly_user }}"
                description: "posix group for wildfly"
                type: "str"
            wildfly_service_name:
                default: "wildfly"
                description: "Systemd service name for wildfly"
                type: "str"
            wildfly_http_port:
                default: "8080"
                description: "Server HTTP port"
                type: "str"
            wildfly_version:
                default: "26.0.0.Final"
                description: "Wildfly version to install"
                type: "str"
            wildfly_home:
                default: "/opt/wildfly/wildfly-{{ wildfly_version }}/"
                description: "Wildfly installation directory"
                type: "str"