argument_specs:
    main:
        options:
            wildfly_subs_check_repo_enable:
                default: "True"
                description: "Enable repo"
                type: "str"
            wildfly_subs_check_repo_disabled:
                default: "{{ wildfly_subs_check_repo_enable }}"
                description: "Disable repo"
                type: "str"
            wildfly_subs_skip_remove:
                default: "False"
                description: "Remove previous installation"
                type: "str"
            wildfly_repos_state_file_homedir:
                default: "/opt"
                description: "path to state file"
                type: "str"
            wildfly_repos_state_file_prefix:
                default: ".eap"
                description: "State filename prefix"
                type: "str"
            wildfly_repos_state_file_suffix:
                default: ".repo"
                description: "State filename suffix"
                type: "str"
            wildfly_rpm_install_root_dir:
                default: "/opt/rh/eap7/"
                description: "Wildfly or JBoss EAP install folder"
                type: "str"
            eap_group_install_name:
                default: "jboss-eap7-jdk11"
                description: "Group install package name"
                type: "str"
