---
- name: "Ensure required parameters are provided"
  ansible.builtin.assert:
    that:
      - wildfly_apps is defined and wildfly_apps | length > 0
    quiet: true

- name: "Check that webapp is available"
  ansible.builtin.include_tasks: app.yml
  loop: "{{ wildfly_apps }}"
  loop_control:
    loop_var: app
