argument_specs:
    main:
        options:
            jdbc_driver_module_dir:
                required: true
                description: "Path for module installation"
                type: "str"
            jdbc_driver_version:
                required: true
                description: "Version of jdbc driver to download"
                type: "str"
            jdbc_driver_jar_filename:
                required: true
                description: "Filename of jdbc driver to download"
                type: "str"
            jdbc_driver_jar_url:
                required: true
                description: "URL for jdbc driver download"
                type: "str"
            jdbc_driver_jar_installation_path:
                required: true
                description: "Path for jdbc driver installation"
                type: "str"
            jdbc_driver_module_name:
                required: true
                description: "Name for the jdbc driver module"
                type: "str"
            wildfly_version:
                default: "29.0.0.Final"
                description: "Wildfly version to install"
                type: "str"
            wildfly_home:
                default: "/opt/wildfly/wildfly-{{ wildfly_version }}/"
                description: "Wildfly installation directory"
                type: "str"
            wildfly_user:
                default: "wildfly"
                description: "posix user account for wildfly"
                type: "str"
            wildfly_group:
                default: "{{ wildfly_user }}"
                description: "posix group for wildfly"
                type: "str"
            override_module_xml_template:
                description: "Override path of template used for module configuration"
                type: "str"
                required: False
    downstream:
        options:
            eap_enable:
                default: True
                description: "Enable install of Red Hat JBoss EAP"
                type: "bool"
            eap_version:
                default: "7.4.0"
                description: "Red Hat EAP version to install"
                type: "str"
            eap_home:
                default: "/opt/jboss_eap/jboss-eap-{{ (eap_version.split('.'))[0:2] | join('.') }}/"
                description: "Red Hat EAP installation path"
                type: "str"
