---
wildfly_subs_check_repo_enable: True
wildfly_subs_check_repo_disabled: "{{ wildfly_subs_check_repo_enable }}"
wildfly_subs_skip_remove: False
wildfly_repos_state_file_homedir: /opt
wildfly_repos_state_file_prefix: .eap
wildfly_repos_state_file_suffix: .repo
wildfly_rpm_install_root_dir: /opt/rh/eap7/
eap_group_install_name: jboss-eap7-jdk11
