---
wildfly_version: '37.0.0.Final'
wildfly_archive_filename: "wildfly-{{ wildfly_version }}.zip"
wildfly_archive_filename_on_controller: true
wildfly_download_baseurl: 'https://github.com/wildfly/wildfly/releases/download'
wildfly_install_workdir: '/opt/wildfly/'
wildfly_install_require_privileges_escalation: true
wildfly_home: "{{ wildfly_install_workdir }}wildfly-{{ wildfly_version }}/"
wildfly_install_download_url: "{{ wildfly_download_baseurl }}/{{ wildfly_version }}/{{ wildfly_archive_filename }}"
wildfly_archive_dir: "{{ wildfly_install_workdir }}"
wildfly_config_base: 'standalone.xml'
wildfly_config_custom_file: ''
wildfly_user: 'wildfly'
wildfly_group: "{{ wildfly_user }}"
wildfly_java_version: 17
wildfly_java_package_name: "java-{{ wildfly_java_version }}-openjdk-headless"
wildfly_install_force_reinstall_config_base: false

# whether to install from local archive
wildfly_offline_install: False
wildfly_prereqs_packages:
  - unzip
  - tar
  - iproute
  - sed
  - sudo
  - tzdata-java

wildfly_instance_name: wildfly
wildfly_selinux_enabled: False
wildfly_cluster_enabled: False
