---
- name: Execute restorecon
  ansible.builtin.command: "restorecon -F -R -v {{ wildfly_install_workdir }}"
  register: selinux_output
  changed_when: selinux_output.stdout_lines | length > 0
  become: "{{ root_permission | default(true) }}"
  when:
    - new_version_downloaded.changed or not path_to_workdir.stat.exists
    - wildfly_selinux_enabled
  listen: exec_restorecon
